"""Export Service - Generates PDF and DOCX ebook files."""

import os
import io
import re
import tempfile
from datetime import datetime
from fpdf import FPDF
from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn

# OTA Brand Colors
OTA_ORANGE = (255, 107, 53)
OTA_BLUE = (30, 58, 138)
OTA_TEAL = (20, 184, 166)
OTA_DARK = (30, 41, 59)


class EbookPDFGenerator:
    """Generate a professional PDF ebook with Bangla support."""

    def __init__(self, design_settings: dict = {}):
        self.font_name = design_settings.get("font", "Helvetica")
        self.header_style = design_settings.get("header_style", "minimal")
        self.footer_style = design_settings.get("footer_style", "standard")
        self.margins = design_settings.get("margins", "standard")
        self.line_spacing = design_settings.get("line_spacing", 1.5)

        margin_map = {"narrow": 12, "standard": 20, "wide": 25, "extra_wide": 30}
        self.margin_mm = margin_map.get(self.margins, 20)

    def generate(
        self,
        title: str,
        subtitle: str,
        author: str,
        press: str,
        website: str,
        chapters: list[dict],
        book_description: str = "",
        about_author: str = "",
    ) -> bytes:
        """Generate PDF and return bytes."""

        class EbookPDF(FPDF):
            def __init__(pdf_self, *args, **kwargs):
                super().__init__(*args, **kwargs)
                pdf_self._book_title = title
                pdf_self._author = author
                pdf_self._press = press
                pdf_self._header_style = self.header_style
                pdf_self._footer_style = self.footer_style
                pdf_self._skip_header = False

            def header(pdf_self):
                if pdf_self._skip_header or pdf_self.page_no() <= 2:
                    return
                pdf_self.set_font("Helvetica", "I", 8)
                pdf_self.set_text_color(*OTA_BLUE)
                pdf_self.cell(0, 8, pdf_self._book_title[:50], new_x="LMARGIN", new_y="NEXT", align="L")
                pdf_self.set_draw_color(*OTA_ORANGE)
                pdf_self.set_line_width(0.3)
                pdf_self.line(
                    pdf_self.l_margin, pdf_self.get_y(),
                    pdf_self.w - pdf_self.r_margin, pdf_self.get_y()
                )
                pdf_self.ln(3)

            def footer(pdf_self):
                if pdf_self.page_no() <= 2:
                    return
                pdf_self.set_y(-15)
                pdf_self.set_font("Helvetica", "I", 8)
                pdf_self.set_text_color(*OTA_BLUE)
                footer_text = f"{pdf_self._author}  |  Page {pdf_self.page_no()}  |  {pdf_self._press}"
                pdf_self.cell(0, 10, footer_text, align="C")

        pdf = EbookPDF(orientation="P", unit="mm", format="A4")
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.set_margins(self.margin_mm, self.margin_mm, self.margin_mm)

        # === TITLE PAGE ===
        pdf.add_page()
        pdf._skip_header = True
        pdf.ln(40)
        pdf.set_font("Helvetica", "B", 28)
        pdf.set_text_color(*OTA_BLUE)
        pdf.cell(0, 15, title, new_x="LMARGIN", new_y="NEXT", align="C")

        if subtitle:
            pdf.set_font("Helvetica", "", 14)
            pdf.set_text_color(*OTA_ORANGE)
            pdf.cell(0, 10, subtitle, new_x="LMARGIN", new_y="NEXT", align="C")

        pdf.ln(20)
        pdf.set_font("Helvetica", "", 12)
        pdf.set_text_color(*OTA_DARK)
        pdf.cell(0, 8, f"By {author}", new_x="LMARGIN", new_y="NEXT", align="C")

        if press:
            pdf.cell(0, 8, press, new_x="LMARGIN", new_y="NEXT", align="C")
        if website:
            pdf.set_text_color(*OTA_TEAL)
            pdf.cell(0, 8, website, new_x="LMARGIN", new_y="NEXT", align="C")

        # === COPYRIGHT PAGE ===
        pdf.add_page()
        pdf.ln(60)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*OTA_DARK)
        year = datetime.now().year
        pdf.cell(0, 6, f"Copyright {year} {author}", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.cell(0, 6, "All rights reserved.", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.cell(0, 6, f"Published by {press}", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.cell(0, 6, f"Generated by OTA Ebook Creator", new_x="LMARGIN", new_y="NEXT", align="C")

        # === TABLE OF CONTENTS ===
        pdf.add_page()
        pdf._skip_header = False
        pdf.set_font("Helvetica", "B", 18)
        pdf.set_text_color(*OTA_BLUE)
        pdf.cell(0, 12, "Table of Contents", new_x="LMARGIN", new_y="NEXT", align="L")
        pdf.ln(5)

        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(*OTA_DARK)
        for i, ch in enumerate(chapters):
            ch_title = ch.get("title", f"Chapter {i+1}")
            pdf.cell(0, 8, f"{i+1}. {ch_title}", new_x="LMARGIN", new_y="NEXT", align="L")

        # === CHAPTER CONTENT ===
        for i, ch in enumerate(chapters):
            pdf.add_page()

            # Chapter title
            pdf.set_font("Helvetica", "B", 22)
            pdf.set_text_color(*OTA_ORANGE)
            pdf.cell(0, 12, f"Chapter {i+1}", new_x="LMARGIN", new_y="NEXT", align="L")

            pdf.set_font("Helvetica", "B", 16)
            pdf.set_text_color(*OTA_BLUE)
            ch_title = ch.get("title", "")
            pdf.cell(0, 10, ch_title, new_x="LMARGIN", new_y="NEXT", align="L")

            pdf.set_draw_color(*OTA_ORANGE)
            pdf.set_line_width(0.5)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + 40, pdf.get_y())
            pdf.ln(8)

            # Content - parse markdown to basic PDF
            content = ch.get("content", "")
            self._render_markdown_to_pdf(pdf, content)

        # === ABOUT AUTHOR ===
        if about_author:
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 18)
            pdf.set_text_color(*OTA_BLUE)
            pdf.cell(0, 12, "About the Author", new_x="LMARGIN", new_y="NEXT", align="L")
            pdf.ln(5)
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(*OTA_DARK)
            pdf.multi_cell(0, 6, about_author)

        # Return bytes
        return bytes(pdf.output())

    def _render_markdown_to_pdf(self, pdf: FPDF, markdown_text: str):
        """Basic markdown to PDF rendering."""
        lines = markdown_text.split("\n")

        for line in lines:
            stripped = line.strip()
            if not stripped:
                pdf.ln(3)
                continue

            # H2 heading
            if stripped.startswith("## "):
                pdf.ln(4)
                pdf.set_font("Helvetica", "B", 14)
                pdf.set_text_color(*OTA_BLUE)
                pdf.multi_cell(0, 7, stripped[3:])
                pdf.ln(2)
                continue

            # H3 heading
            if stripped.startswith("### "):
                pdf.ln(3)
                pdf.set_font("Helvetica", "B", 12)
                pdf.set_text_color(*OTA_ORANGE)
                pdf.multi_cell(0, 6, stripped[4:])
                pdf.ln(2)
                continue

            # Blockquote
            if stripped.startswith("> "):
                pdf.set_font("Helvetica", "I", 10)
                pdf.set_text_color(100, 100, 100)
                pdf.set_x(pdf.l_margin + 10)
                pdf.multi_cell(0, 5.5, stripped[2:])
                pdf.ln(2)
                continue

            # Bullet point
            if stripped.startswith("- ") or stripped.startswith("* "):
                pdf.set_font("Helvetica", "", 10.5)
                pdf.set_text_color(*OTA_DARK)
                pdf.set_x(pdf.l_margin + 5)
                pdf.multi_cell(0, 5.5, f"  {stripped}")
                continue

            # Pro Tip
            if "Pro Tip" in stripped or "প্রো টিপ" in stripped:
                pdf.ln(2)
                pdf.set_fill_color(255, 248, 240)
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(*OTA_ORANGE)
                pdf.multi_cell(0, 6, stripped, fill=True)
                pdf.ln(2)
                continue

            # Regular paragraph
            pdf.set_font("Helvetica", "", 10.5)
            pdf.set_text_color(*OTA_DARK)
            # Remove markdown bold/italic
            clean = re.sub(r'\*\*(.+?)\*\*', r'\1', stripped)
            clean = re.sub(r'\*(.+?)\*', r'\1', clean)
            pdf.multi_cell(0, 5.5, clean)
            pdf.ln(1)


class EbookDOCXGenerator:
    """Generate a professional DOCX ebook."""

    def generate(
        self,
        title: str,
        subtitle: str,
        author: str,
        press: str,
        website: str,
        chapters: list[dict],
        book_description: str = "",
        about_author: str = "",
        design_settings: dict = {},
    ) -> bytes:
        doc = Document()

        # Page margins
        for section in doc.sections:
            section.top_margin = Cm(2.5)
            section.bottom_margin = Cm(2.5)
            section.left_margin = Cm(2.5)
            section.right_margin = Cm(2.5)

        # === TITLE PAGE ===
        doc.add_paragraph()
        doc.add_paragraph()

        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(title)
        run.bold = True
        run.font.size = Pt(28)
        run.font.color.rgb = RGBColor(*OTA_BLUE)

        if subtitle:
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run(subtitle)
            run.font.size = Pt(14)
            run.font.color.rgb = RGBColor(*OTA_ORANGE)

        doc.add_paragraph()
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(f"By {author}")
        run.font.size = Pt(12)

        if press:
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run(press)
            run.font.size = Pt(11)

        if website:
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run(website)
            run.font.size = Pt(10)
            run.font.color.rgb = RGBColor(*OTA_TEAL)

        doc.add_page_break()

        # === COPYRIGHT ===
        doc.add_paragraph()
        year = datetime.now().year
        for line in [
            f"Copyright {year} {author}",
            "All rights reserved.",
            f"Published by {press}",
            "Generated by OTA Ebook Creator | www.onlinetechacademy.com",
        ]:
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run(line)
            run.font.size = Pt(9)

        doc.add_page_break()

        # === TABLE OF CONTENTS ===
        h = doc.add_heading("Table of Contents", level=1)
        for run in h.runs:
            run.font.color.rgb = RGBColor(*OTA_BLUE)

        for i, ch in enumerate(chapters):
            p = doc.add_paragraph(f"{i+1}. {ch.get('title', '')}")
            for run in p.runs:
                run.font.size = Pt(11)

        doc.add_page_break()

        # === CHAPTERS ===
        for i, ch in enumerate(chapters):
            # Chapter heading
            h = doc.add_heading(f"Chapter {i+1}: {ch.get('title', '')}", level=1)
            for run in h.runs:
                run.font.color.rgb = RGBColor(*OTA_BLUE)

            # Content
            content = ch.get("content", "")
            self._render_markdown_to_docx(doc, content)

            if i < len(chapters) - 1:
                doc.add_page_break()

        # === ABOUT AUTHOR ===
        if about_author:
            doc.add_page_break()
            h = doc.add_heading("About the Author", level=1)
            for run in h.runs:
                run.font.color.rgb = RGBColor(*OTA_BLUE)
            doc.add_paragraph(about_author)

        # Save to bytes
        buffer = io.BytesIO()
        doc.save(buffer)
        return buffer.getvalue()

    def _render_markdown_to_docx(self, doc: Document, markdown_text: str):
        """Basic markdown to DOCX rendering."""
        lines = markdown_text.split("\n")

        for line in lines:
            stripped = line.strip()
            if not stripped:
                continue

            if stripped.startswith("## "):
                h = doc.add_heading(stripped[3:], level=2)
                for run in h.runs:
                    run.font.color.rgb = RGBColor(*OTA_BLUE)

            elif stripped.startswith("### "):
                h = doc.add_heading(stripped[4:], level=3)
                for run in h.runs:
                    run.font.color.rgb = RGBColor(*OTA_ORANGE)

            elif stripped.startswith("> "):
                p = doc.add_paragraph()
                try:
                    p.style = doc.styles["Quote"]
                except KeyError:
                    pass
                run = p.add_run(stripped[2:])
                run.italic = True
                run.font.size = Pt(10)

            elif stripped.startswith("- ") or stripped.startswith("* "):
                doc.add_paragraph(stripped[2:], style="List Bullet")

            elif "Pro Tip" in stripped or "প্রো টিপ" in stripped:
                p = doc.add_paragraph()
                run = p.add_run(stripped)
                run.bold = True
                run.font.color.rgb = RGBColor(*OTA_ORANGE)
                run.font.size = Pt(10)

            else:
                # Remove markdown formatting
                clean = re.sub(r'\*\*(.+?)\*\*', r'\1', stripped)
                clean = re.sub(r'\*(.+?)\*', r'\1', clean)
                p = doc.add_paragraph(clean)
                for run in p.runs:
                    run.font.size = Pt(11)


def generate_pdf(
    title: str, subtitle: str, author: str, press: str, website: str,
    chapters: list[dict], design_settings: dict = {},
    book_description: str = "", about_author: str = "",
) -> bytes:
    """Convenience function to generate PDF."""
    gen = EbookPDFGenerator(design_settings)
    return gen.generate(title, subtitle, author, press, website, chapters, book_description, about_author)


def generate_docx(
    title: str, subtitle: str, author: str, press: str, website: str,
    chapters: list[dict], design_settings: dict = {},
    book_description: str = "", about_author: str = "",
) -> bytes:
    """Convenience function to generate DOCX."""
    gen = EbookDOCXGenerator()
    return gen.generate(title, subtitle, author, press, website, chapters, book_description, about_author, design_settings)
